### ISSUE TITLE
Trigger is sent before merge commit exists

### ISSUE THREAD

**Issue by dgreenbean** [wparad/stash-http-request-trigger#4]
Every Stash pull request gets a hidden merge commit (refs/heads/pull-requests/123/merge) in addition to the source commit.  This plugin triggers the HTTP call before the merge commit is created in some instances.  This happens particularly when there is a large commit.  By waiting to trigger the call, the receiver can be assured that, unless there is a merge conflict, a merge commit exists.  Ideally, there would be an option to not trigger the call when there is a merge conflict.

**Comment by wparad** [comment]
I'm aware of the hidden merge ref, but I am not sure how to incorporate that into what you are asking.  
Are you asking to not trigger if there is a merge conflict?  Does stash provide you a way to do this?

**Comment by dgreenbean** [comment]
There are two independent features here, in order of importance:
* Wait to trigger until a merge commit exists or a merge conflict is detected.
* Optionally, based on settings, do not trigger if a merge conflict is detected.

I wish I had a sense of how to accomplish this.  Certainly, the information should be available somewhere in Stash.  The last time I tried to look, though, it wasn't clear.

**Comment by wparad** [comment]
I don't think this is possible at all:
* [Stash pull request](https://developer.atlassian.com/static/javadoc/stash.old-perms-pre-feb4/latest/api/reference/com/atlassian/stash/pull/PullRequest.html) doesn't contain any information about the merge.  If the merge ref is created in the background, the pull-in can't wait and poll for that without sending that information to a async background task.  I am not sure I want to wait for something like that before sending the trigger, but maybe that could be an option.
 * Change the on pull request event triggers to create the POST in the background only after a number of validation steps.

I can try implementing this if you can point to service that has an API for converting the string `refs/pull-requests/PR_ID/merge` to an actual ref check so that I can validate its status.

**Comment by dgreenbean** [comment]
I'll switch to doing the merge in the build system.  This feels less reliable to me, but I can't think of any reason why it shouldn't work.  I agree that the Stash API is not conducive to this feature.
